# Generated by Django 2.2.6 on 2020-02-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20200217_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
