# Generated by Django 2.2.6 on 2020-02-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_auto_20200217_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='name',
            field=models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')]),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='meal_name',
            field=models.IntegerField(choices=[(0, 'Śniadanie'), (1, 'Drugie śniadanie'), (2, 'Obiad'), (3, 'Podwieczorek'), (4, 'Kolacja')]),
        ),
    ]
