# Generated by Django 2.2.6 on 2020-02-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_auto_20200218_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeplan',
            name='order',
        ),
    ]
