# Generated by Django 2.2.6 on 2020-02-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_page'),
        ('jedzonko', '0010_auto_20200218_1420'),
    ]

    operations = [
    ]
