# Generated by Django 2.2.6 on 2020-02-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0010_auto_20200218_1420'),
        ('jedzonko', '0007_page'),
    ]

    operations = [
    ]
